---
- block:
  - name: create mysql database
    mysql_db:
      name: "{{ openstack_oslo_db_name }}"
      state: present
  - name: create mysql user
    mysql_user:
      name: "{{ openstack_oslo_db_username }}"
      password: "{{ openstack_oslo_db_password }}"
      priv: "{{ openstack_oslo_db_name }}.*:ALL"
      state: present
  when: openstack_oslo_db_manage == True

- name: configure database
  ini_file:
    dest: "{{ __openstack_keystone_config_file }}"
    section: database
    option: connection
    value: "mysql+pymysql://{{ openstack_oslo_db_username }}:{{ openstack_oslo_db_password }}@localhost/{{ openstack_oslo_db_name }}"
  with_items: "{{ openstack_oslo_db_config_files }}"
  register: openstack_oslo_db_config_result
...
